services:
  dev-workspace:
    container_name: "dev-worksapce"
    # For development
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        POETRY_VERSION: ${POETRY_VERSION}
        CUDA_VERSION: ${CUDA_VERSION}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        ROOT_DIR: ${ROOT_DIR}
    profiles:
      - dev
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DISABLE_REQUIRE=1
    volumes:
      - .${ROOT_DIR}:${ROOT_DIR}
      - dev-venv:${ROOT_DIR}/.venv
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  
  prod-workspace:
    container_name: "prod-worksapce"
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        POETRY_VERSION: ${POETRY_VERSION}
        CUDA_VERSION: ${CUDA_VERSION}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        ROOT_DIR: ${ROOT_DIR}
    profiles:
      - prod
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DISABLE_REQUIRE=1
    volumes:
      - .${ROOT_DIR}:${ROOT_DIR}
      - prod-venv:${ROOT_DIR}/.venv
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  # jekyll:
  #   container_name: "jekyll-docs"
  #   build: ./docs
  #   volumes:
  #     - ./docs:/site
  #   ports:
  #     - '4000:4000'
volumes:
  dev-venv:
  prod-venv:

    