source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins
# gem "jekyll-readme-index"
gem "just-the-docs", "~> 0.8.1"
gem "webrick", "~> 1.8"
